version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: coin_flip_casino_db
    environment:
      POSTGRES_DB: coin_flip_casino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: