version: '3'

services:
  # PostgreSQL Database
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: coingame
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Spring Boot Application
  app:
    image: coin-flip-casino:latest  # You'll need to build this image
    restart: always
    env_file:
      - .env.prod  # Use the production environment file
    depends_on:
      - db
    ports:
      - "${PORT}:8080"
    networks:
      - app-network

  # Frontend Application (Optional, if you want to containerize it)
  frontend:
    image: coin-flip-frontend:latest  # You'll need to build this image
    restart: always
    ports:
      - "80:80"
    environment:
      - API_URL=http://app:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: